export const reactNativeTopics:String[] = [
    "React Native Basics",
    "Components and Props",
    "State and Lifecycle",
    "Handling Touches",
    "User Interface Styling",
    "Lists and FlatList",
    "Navigation in React Native",
    "React Navigation Library",
    "Redux for State Management",
    "AsyncStorage for Data Persistence",
    "Networking and Fetch API",
    "Working with Forms",
    "Gesture Handling",
    "Animations in React Native",
    "React Native CLI",
    "Expo for React Native",
    "Building and Publishing Apps",
    "Debugging Techniques",
    "Error Handling",
    "Localization and Internationalization",
    "Authentication in React Native",
    "Push Notifications",
    "Using Native Modules",
    "React Native Performance Optimization",
    "Unit Testing in React Native",
    "Continuous Integration (CI) in React Native",
    "App Deployment Strategies",
    "Building Cross-Platform Apps",
    "Accessibility in React Native",
    "Augmented Reality (AR) in React Native",
];

// You can access each topic like this:
